// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ2ntZyC-a7z_JugcyF6CTaUMaUuZqemM',
    appId: '1:304863472803:web:1c4762eb594ecb4b9e2316',
    messagingSenderId: '304863472803',
    projectId: 'agrivision-85945',
    authDomain: 'agrivision-85945.firebaseapp.com',
    storageBucket: 'agrivision-85945.firebasestorage.app',
    measurementId: 'G-2HVYPSX4RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMNtyJr18QVDS1uV6zDjMAAysRt-QoWfU',
    appId: '1:304863472803:android:709d639ab0b592709e2316',
    messagingSenderId: '304863472803',
    projectId: 'agrivision-85945',
    storageBucket: 'agrivision-85945.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBITk95700PAaADuD5ZeDKeErndlqh4gG0',
    appId: '1:304863472803:ios:bf31bf658dea8a579e2316',
    messagingSenderId: '304863472803',
    projectId: 'agrivision-85945',
    storageBucket: 'agrivision-85945.firebasestorage.app',
    iosBundleId: 'com.example.agriVision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBITk95700PAaADuD5ZeDKeErndlqh4gG0',
    appId: '1:304863472803:ios:bf31bf658dea8a579e2316',
    messagingSenderId: '304863472803',
    projectId: 'agrivision-85945',
    storageBucket: 'agrivision-85945.firebasestorage.app',
    iosBundleId: 'com.example.agriVision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ2ntZyC-a7z_JugcyF6CTaUMaUuZqemM',
    appId: '1:304863472803:web:7fa362a7b633fd1c9e2316',
    messagingSenderId: '304863472803',
    projectId: 'agrivision-85945',
    authDomain: 'agrivision-85945.firebaseapp.com',
    storageBucket: 'agrivision-85945.firebasestorage.app',
    measurementId: 'G-TD3MT4W6FF',
  );
}
